name: hopwhistle
region: nyc
services:
  - name: api
    github:
      repo: bbarnes4318/hopwhistle
      branch: master
      deploy_on_push: true
    source_dir: /
    run_command: pnpm --filter @hopwhistle/api start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    health_check:
      http_path: /health
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '3001'
      - key: HOST
        value: '0.0.0.0'
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: S3_ENDPOINT
        scope: RUN_TIME
        type: SECRET
      - key: S3_BUCKET
        scope: RUN_TIME
        type: SECRET
      - key: S3_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: S3_REGION
        value: 'us-east-1'
      - key: S3_FORCE_PATH_STYLE
        value: 'false'
      - key: SIGNALWIRE_PROJECT_ID
        scope: RUN_TIME
        type: SECRET
      - key: SIGNALWIRE_API_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: SIGNALWIRE_SPACE_URL
        scope: RUN_TIME
        type: SECRET
      - key: RTPENGINE_URL
        scope: RUN_TIME
        type: SECRET
      - key: FREESWITCH_ESL_HOST
        scope: RUN_TIME
        type: SECRET
      - key: FREESWITCH_ESL_PORT
        value: '8021'
      - key: FREESWITCH_ESL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: CLICKHOUSE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CLICKHOUSE_USER
        value: 'default'
      - key: CLICKHOUSE_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: CLICKHOUSE_DATABASE
        value: 'hopwhistle_analytics'
      - key: RECORDING_HOT_TO_WARM_DAYS
        value: '30'
      - key: RECORDING_WARM_TO_COLD_DAYS
        value: '90'
      - key: RECORDING_RETENTION_DAYS
        value: '365'
      - key: RECORDING_LIFECYCLE_ENABLED
        value: 'true'
      - key: LOG_LEVEL
        value: 'info'
      - key: ENABLE_TRACING
        value: 'false'
      - key: JAEGER_ENDPOINT
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: TWILIO_API_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: TRUSTEDFORM_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JORNAYA_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_ENABLED
        value: 'false'
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_HOST
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PORT
        value: '587'
      - key: SMTP_SECURE
        value: 'false'
      - key: SMTP_USER
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: SMTP_FROM
        value: 'noreply@hopwhistle.com'
      - key: DEFAULT_TENANT_ID
        scope: RUN_TIME
        type: SECRET
    build_command: |
      corepack enable
      corepack prepare pnpm@8.15.0 --activate
      pnpm install --frozen-lockfile
      pnpm --filter @hopwhistle/api db:generate
      pnpm --filter @hopwhistle/api build

  - name: web
    github:
      repo: bbarnes4318/hopwhistle
      branch: master
      deploy_on_push: true
    source_dir: /
    run_command: pnpm --filter @hopwhistle/web start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_WS_URL
        scope: RUN_TIME
        type: SECRET
      - key: NEXT_PUBLIC_APP_NAME
        value: 'Hopwhistle'
      - key: NEXT_PUBLIC_API_KEY
        scope: RUN_TIME
        type: SECRET
    build_command: |
      corepack enable
      corepack prepare pnpm@8.15.0 --activate
      pnpm install --frozen-lockfile
      pnpm --filter @hopwhistle/web build

  - name: worker
    github:
      repo: bbarnes4318/hopwhistle
      branch: master
      deploy_on_push: true
    source_dir: /
    run_command: pnpm --filter @hopwhistle/worker start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 9091
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
        type: SECRET
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
        type: SECRET
      - key: WORKER_CONCURRENCY
        value: '5'
      - key: METRICS_PORT
        value: '9091'
      - key: CLICKHOUSE_URL
        scope: RUN_TIME
        type: SECRET
      - key: CLICKHOUSE_USER
        value: 'default'
      - key: CLICKHOUSE_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: CLICKHOUSE_DATABASE
        value: 'hopwhistle_analytics'
      - key: LOG_LEVEL
        value: 'info'
      - key: ENABLE_TRACING
        value: 'false'
      - key: JAEGER_ENDPOINT
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_ENABLED
        value: 'false'
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
    build_command: |
      corepack enable
      corepack prepare pnpm@8.15.0 --activate
      pnpm install --frozen-lockfile
      pnpm --filter @hopwhistle/worker build

databases:
  - name: db
    engine: PG
    version: '16'
    production: false
    cluster_name: hopwhistle-db
    db_name: hopwhistle
    db_user: hopwhistle

  - name: redis
    engine: REDIS
    version: '7'
    production: false
    cluster_name: hopwhistle-redis
